### ISSUE TITLE
-0 -0 -0 coordinates

### ISSUE THREAD

**Issue by N1zyx3** [simply-kel/ActionBarInfo#2]
# Russian
Не знаю, может это так и запланировано но играя можно встать на "-0 -0 -0" координаты (по версии мода). Если с по икс и зет -0 (Координаты от мода) это -1 (Верные координаты), то по игрек -0 это именно 0.50. Ниже -1, выше 0

# English
I don’t know, maybe this is planned, but when playing you can stand on the “-0 -0 -0” coordinates (according to the mod version). If X and Z -0 (Coordinates from the mod) is -1 (Correct coordinates), then Y -0 is exactly 0.50. Below -1, above 0
![bug](https://github.com/simply-kel/ActionBarInfo/assets/114083567/06e83247-9928-4dff-8309-89b59cc2692b)

**Comment by kel-cu** [comment]
Я сам не знаю точно, я беру точные координаты у игрока, далее укругляю.
Так-же хотелось бы узнать какая у вас версия мода

**Comment by kel-cu** [comment]
Сейчас посмотрел, и координаты сходятся с меню F3
![image](https://github.com/simply-kel/ActionBarInfo/assets/86980879/ac3ec995-a9d2-4933-a773-9c9a31d5cd7d)

Так что возможно мод который вы используете на HUD с координатами округляет с правилами математики 0.5 -> 1

**Comment by N1zyx3** [comment]
Версия мода: последняя на 1.20.1 на modrinth (1.1.0). По поводу HUD не знаю, по тем же законам математики нету цифры -0, по этому у меня и возник вопрос. Да и мне как человеку, постоянно пользующемуся командой fill (и остальными командами-заменителями) как то не удобно. Придётся видимо привыкать

**Comment by kel-cu** [comment]
Возможно в следующих версиях добавлю варианты вывода координат

**Comment by N1zyx3** [comment]
Хорошо, спасибо
