### ISSUE TITLE
Make 1.19.3 version?

### ISSUE THREAD

**Issue by ExiledLizard** [simply-kel/ActionBarInfo#4]
I am just requesting you to release a version of the mod: "Action-bar Info", for 1.19.3.

**Comment by kel-cu** [comment]
I'm not going to make a port to 1.19.3 as everything is adapted to the new version, including the library

**Comment by ExiledLizard** [comment]
Alr, thanks for responding.

**Comment by kel-cu** [comment]
*I removed the extra information from the e-mail just in case
