### ISSUE TITLE
incorrect coordinates

### ISSUE THREAD

**Issue by rAfEkk** [simply-kel/ActionBarInfo#6]
incorrect coordinates in actionbarinfo compared to f3
![изображение](https://github.com/user-attachments/assets/2c36c485-f343-4f4f-8e8f-9f7e4dea215f)

mod version: 1.3.0-alpha.2+mc1.20.1

**Comment by kel-cu** [comment]
Это функция стелса из AlinLib, которая включается биндом или через конфиги

**Comment by rAfEkk** [comment]
ааа, понял, спасибо
